WIP image attachment
AgileVentures/kcsc_api pull request #9
Opened 2021-08-31 13:50 UTC by tochman

2021-09-01 07:16 UTC, SevaDer14 requested changes
seems good, can add one more test.

2021-09-01 07:16 UTC, SevaDer14 commented on spec/requests/api/articles/create_spec.rb
can add test for attaching image
```
it 'is expected to have attached an image' do
      article = Article.last
      expect(article.image.attached?).to eq true
    end
```

2021-09-02 06:50 UTC, SevaDer14 commented on spec/models/image_spec.rb
> +    # end
comment

2021-09-02 07:36 UTC, tochman commented on spec/models/image_spec.rb
> +    # end
Done

2021-09-02 08:03 UTC, SevaDer14 approved these changes

2021-09-02 08:04 UTC, merged